config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/terms', to: 'static_pages#terms'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jobposting.rb
class Jobposting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @current_jobs = Jobposting.all
  end

  def about
  end

  def privacy
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="w-full h-auto pin-b">
  <div>
    <div class="flex">
      <div class="w-1/3 pl-4">
        <address class="text-xs mt-2">
        Henry Care
        <!-- <br>123 Main Street
        <br>456 East Hall
        <br>Ann Arbor, MI 48109-1043 -->
        </address>
      </div>
      <div class="w-1/3 mt-2 mx-auto flex justify-center">
        <!-- 734.647.0000 - voice
         <br> -->
        <%= mail_to "rhsmoke@gmail.com","Questions?" %>
      </div>
      <div class="w-1/3 flex justify-end">
        <% if admin_user_signed_in? %>
          <ul>
            <li>
              <%= link_to 'Admin Dashboard', admin_root_path, class: "mt-2 pr-4" %>
            </li>
            <li>
              <%= link_to destroy_admin_user_session_path, method: :delete do  %>
                <%= render :partial => 'svg/open_padlock' %>
                <span>Admin Sign_out</span>
              <% end %>
            </li>
          </ul>
        <% else %>
          <%= link_to new_admin_user_session_path do  %>
            <%= render :partial => 'svg/closed_padlock' %>
            <span class='pr-4'>Admin Sign_in</span>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="w-full flex justify-center">
      <div class="copyright">
        Copyright <%= Time.now.year %> | <%= link_to 'Get Smoke Signals', '#' %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="w-full h-auto">
  <nav class="flex items-center justify-between flex-wrap bg-green-700 p-6">
    <div class="flex items-center flex-no-shrink text-white mr-6">
      <%= link_to root_path do  %>
        <%= render :partial => 'svg/henrycare' %>
      <% end %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border rounded text-teal-lighter border-teal-light hover:text-white hover:border-white">
        <svg class="h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
      <div class="text-sm lg:flex-grow">
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white mr-4">
          <%= link_to "About", about_path %>
        </a>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white mr-4">
          <%= link_to "Privacy", privacy_path %>
        </a>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white">
          <%= link_to "Terms of Use", terms_path %>
        </a>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_notification.html.erb
<% flash.each do |key, value| %>
  <% if key == 'alert' or key == 'notice' %>
    <%= content_tag(:div, value, class: "flash #{key}", id: "#{key}") %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='h-full'>
  <head>
    <title>Henry Care</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <noscript>
      <meta http-equiv="refresh" content="2;url=nojavascript.html">
    </noscript>

  </head>
  <body class='flex flex-col h-full'>
    <%= render 'layouts/header' %>
    <main class="flex-1 mx-auto px-2">
      <%= render 'layouts/notification' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About the application</h1>
<p>
  Henry care is a means for finding and supporitng caregivers who work with my father and mother. 
</p>

app/views/static_pages/home.html.erb
<h1 class="text-3xl font-bold text-center my-20">We are seeking dependable, kind, morning and bedtime caregivers.</h1>
<ul class='list-disc'>
    <li>Flexible part-time schedule.</li>
    <li>Pleasant home environment with appreciative people.</li>
    <li>Pay starting at $16/hr; $24/hr for holidays and back-up fill-in</li>
    <ul class='list-none'>
        <li>4hr. AM shift 8:00AM - Noon</li>
        <li>2hr. PM shift 8:00PM - 10:00PM</li>
    </ul>
    <li>We need to fill a 7-day schedule; holidays pay time-and-a-half</li>
</ul>
<p>Henry is a pleasant man with limited mobility. He uses a power wheelchair and needs 
help getting in/out of bed in the morning and at night, with bathing, dressing, 
changing his colostomy bag/condom catheter.
</p>

<p>He also needs help with daily exercises. Other duties include prepping light 
breakfast in the morning and light clean-up detail.</p>

<p>Henry lives with his wife, Therese, in White Lake. Family is active in 
his care and available to help with any questions or concerns.
</p>
<hr>
<% if @current_jobs %>
  <ul>
    <% @current_jobs.each do |app| %>
      <li>
        <%= button_to app.name, app.url %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>We are currently not accepting applications</p>
<% end%>

app/views/static_pages/privacy.erb
<h1>Website Privacy Notice</h1>
<h4>Overview</h4>
<strong>Privacy Policy</strong> 
<p>
  Richard Smoke built the HenryCare app as
  a Free app. This SERVICE is provided by
  Richard Smoke at no cost and is intended for use as
  is.
</p> <p>
  This page is used to inform visitors regarding my
  policies with the collection, use, and disclosure of Personal
  Information if anyone decided to use my Service.
</p> <p>
  If you choose to use my Service, then you agree to
  the collection and use of information in relation to this
  policy. The Personal Information that I collect is
  used for providing and improving the Service. I will not use or share your information with
  anyone except as described in this Privacy Policy.
</p> <p>
  The terms used in this Privacy Policy have the same meanings
  as in our Terms and Conditions, which is accessible at
  HenryCare unless otherwise defined in this Privacy Policy.
</p> <p><strong>Information Collection and Use</strong></p> <p>
  For a better experience, while using our Service, I
  may require you to provide us with certain personally
  identifiable information. The information that
  I request will be retained on your device and is not collected by me in any way.
</p> <!----> <p><strong>Log Data</strong></p> <p>
  I want to inform you that whenever you
  use my Service, in a case of an error in the app
  I collect data and information (through third party
  products) on your phone called Log Data. This Log Data may
  include information such as your device Internet Protocol
  (“IP”) address, device name, operating system version, the
  configuration of the app when utilizing my Service,
  the time and date of your use of the Service, and other
  statistics.
</p> <p><strong>Cookies</strong></p> <p>
  Cookies are files with a small amount of data that are
  commonly used as anonymous unique identifiers. These are sent
  to your browser from the websites that you visit and are
  stored on your device's internal memory.
</p> <p>
  This Service does not use these “cookies” explicitly. However,
  the app may use third party code and libraries that use
  “cookies” to collect information and improve their services.
  You have the option to either accept or refuse these cookies
  and know when a cookie is being sent to your device. If you
  choose to refuse our cookies, you may not be able to use some
  portions of this Service.
</p> <p><strong>Service Providers</strong></p> <p>
  I may employ third-party companies and
  individuals due to the following reasons:
</p> <ul><li>To facilitate our Service;</li> <li>To provide the Service on our behalf;</li> <li>To perform Service-related services; or</li> <li>To assist us in analyzing how our Service is used.</li></ul> <p>
  I want to inform users of this Service
  that these third parties have access to your Personal
  Information. The reason is to perform the tasks assigned to
  them on our behalf. However, they are obligated not to
  disclose or use the information for any other purpose.
</p> <p><strong>Security</strong></p> <p>
  I value your trust in providing us your
  Personal Information, thus we are striving to use commercially
  acceptable means of protecting it. But remember that no method
  of transmission over the internet, or method of electronic
  storage is 100% secure and reliable, and I cannot
  guarantee its absolute security.
</p> <p><strong>Links to Other Sites</strong></p> <p>
  This Service may contain links to other sites. If you click on
  a third-party link, you will be directed to that site. Note
  that these external sites are not operated by me.
  Therefore, I strongly advise you to review the
  Privacy Policy of these websites. I have
  no control over and assume no responsibility for the content,
  privacy policies, or practices of any third-party sites or
  services.
</p> <p><strong>Children’s Privacy</strong></p> <p>
  These Services do not address anyone under the age of 13.
  I do not knowingly collect personally
  identifiable information from children under 13 years of age. In the case
  I discover that a child under 13 has provided
  me with personal information, I immediately
  delete this from our servers. If you are a parent or guardian
  and you are aware that your child has provided us with
  personal information, please contact me so that
  I will be able to do necessary actions.
</p> <p><strong>Changes to This Privacy Policy</strong></p> <p>
  I may update our Privacy Policy from
  time to time. Thus, you are advised to review this page
  periodically for any changes. I will
  notify you of any changes by posting the new Privacy Policy on
  this page.
</p> <p>This policy is effective as of 2021-03-27</p> <p><strong>Contact Us</strong></p> <p>
  If you have any questions or suggestions about my
  Privacy Policy, do not hesitate to contact me at rhsmoke@gmail.com.
</p> <p>This privacy policy page was created at <a href="https://privacypolicytemplate.net" target="_blank" rel="noopener noreferrer">privacypolicytemplate.net </a>and modified/generated by <a href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer">App Privacy Policy Generator</a></p>

app/views/static_pages/terms.html.erb
<h1>Responsible Use Agreement</h1>
<strong>Terms &amp; Conditions</strong> 
<p>
  By downloading or using the app, these terms will
  automatically apply to you – you should make sure therefore
  that you read them carefully before using the app. You’re not
  allowed to copy, or modify the app, any part of the app, or
  our trademarks in any way. You’re not allowed to attempt to
  extract the source code of the app, and you also shouldn’t try
  to translate the app into other languages, or make derivative
  versions. The app itself, and all the trade marks, copyright,
  database rights and other intellectual property rights related
  to it, still belong to Richard Smoke.
</p> <p>
  Richard Smoke is committed to ensuring that the app is
  as useful and efficient as possible. For that reason, we
  reserve the right to make changes to the app or to charge for
  its services, at any time and for any reason. We will never
  charge you for the app or its services without making it very
  clear to you exactly what you’re paying for.
</p> <p>
  The HenryCare app stores and processes personal data that
  you have provided to us, in order to provide my
  Service. It’s your responsibility to keep your phone and
  access to the app secure. We therefore recommend that you do
  not jailbreak or root your phone, which is the process of
  removing software restrictions and limitations imposed by the
  official operating system of your device. It could make your
  phone vulnerable to malware/viruses/malicious programs,
  compromise your phone’s security features and it could mean
  that the HenryCare app won’t work properly or at all.
</p> <!----> <p>
  You should be aware that there are certain things that
  Richard Smoke will not take responsibility for. Certain
  functions of the app will require the app to have an active
  internet connection. The connection can be Wi-Fi, or provided
  by your mobile network provider, but Richard Smoke
  cannot take responsibility for the app not working at full
  functionality if you don’t have access to Wi-Fi, and you don’t
  have any of your data allowance left.
</p> <p></p> <p>
  If you’re using the app outside of an area with Wi-Fi, you
  should remember that your terms of the agreement with your
  mobile network provider will still apply. As a result, you may
  be charged by your mobile provider for the cost of data for
  the duration of the connection while accessing the app, or
  other third party charges. In using the app, you’re accepting
  responsibility for any such charges, including roaming data
  charges if you use the app outside of your home territory
  (i.e. region or country) without turning off data roaming. If
  you are not the bill payer for the device on which you’re
  using the app, please be aware that we assume that you have
  received permission from the bill payer for using the app.
</p> <p>
  Along the same lines, Richard Smoke cannot always take
  responsibility for the way you use the app i.e. You need to
  make sure that your device stays charged – if it runs out of
  battery and you can’t turn it on to avail the Service,
  Richard Smoke cannot accept responsibility.
</p> <p>
  With respect to Richard Smoke’s responsibility for your
  use of the app, when you’re using the app, it’s important to
  bear in mind that although we endeavour to ensure that it is
  updated and correct at all times, we do rely on third parties
  to provide information to us so that we can make it available
  to you. Richard Smoke accepts no liability for any
  loss, direct or indirect, you experience as a result of
  relying wholly on this functionality of the app.
</p> <p>
  At some point, we may wish to update the app. The app is
  currently available on Android – the requirements for
  system(and for any additional systems we
  decide to extend the availability of the app to) may change,
  and you’ll need to download the updates if you want to keep
  using the app. Richard Smoke does not promise that it
  will always update the app so that it is relevant to you
  and/or works with the Android version that you have
  installed on your device. However, you promise to always
  accept updates to the application when offered to you, We may
  also wish to stop providing the app, and may terminate use of
  it at any time without giving notice of termination to you.
  Unless we tell you otherwise, upon any termination, (a) the
  rights and licenses granted to you in these terms will end;
  (b) you must stop using the app, and (if needed) delete it
  from your device.
</p> <p><strong>Changes to This Terms and Conditions</strong></p> <p>
  I may update our Terms and Conditions
  from time to time. Thus, you are advised to review this page
  periodically for any changes. I will
  notify you of any changes by posting the new Terms and
  Conditions on this page.
</p> <p>
  These terms and conditions are effective as of 2021-03-27
</p> <p><strong>Contact Us</strong></p> <p>
  If you have any questions or suggestions about my
  Terms and Conditions, do not hesitate to contact me
  at rhsmoke@gmail.com.
</p> 
<p>This Terms and Conditions page was generated by <a href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer">App Privacy Policy Generator</a></p>

  

app/views/svg/_closed_padlock.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 fill-current" viewBox="0 0 20 20" >
  <path
  fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" 
  clip-rule="evenodd" 
  stroke="blue-um-blue"
  />
</svg>

app/views/svg/_home_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 fill-current" viewBox="0 0 20 20" >
  <path
  fill-rule="evenodd" d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" 
  clip-rule="evenodd" 
  stroke="blue-um-blue"
  />
</svg>

app/views/svg/_open_padlock.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 fill-current" viewBox="0 0 20 20" >
  <path
  fill-rule="evenodd" d="M10 2a5 5 0 00-5 5v2a2 2 0 00-2 2v5a2 2 0 002 2h10a2 2 0 002-2v-5a2 2 0 00-2-2H7V7a3 3 0 015.905-.75 1 1 0 001.937-.5A5.002 5.002 0 0010 2z" 
  clip-rule="evenodd" 
  stroke="blue-um-blue"
  />
</svg>